services:
  - type: web
    name: joker-prediction-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_with_real_data.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
